### ISSUE TITLE
Checklist for release 

### ISSUE THREAD

**Issue by munkm** [conda-forge/cyclus-feedstock#73]
### Comment:

We are currently trying to get a new release of cyclus out. There are several changes to the recipe that probably need to happen too. Here's what I see: 

- [ ] The shell script with additional information for building cyclus should reflect our current practices. https://github.com/conda-forge/cyclus-feedstock/blob/main/recipe/build.sh#L15-L26
- [ ] The feedstock maintainers in `meta.yaml` include people who aren't super active any more. Do we want to change that? 
- [ ] In `runtests.sh` all of the nosetests lines should be changed to `python -m pytest` 
- [ ] Remove pinning of all dependency versions

**Comment by gonuke** [comment]
Perhaps you're already familiar with this, but conda-forge does have a process for testing release candidates that doesn't get in the way of real releases: https://conda-forge.org/docs/maintainer/knowledge_base/#pre-release-builds

I've done it once, but only once, so I don't really recall how it goes and/or if it's smooth...

**Comment by munkm** [comment]
I actually forgot that this existed!!
